name: Build Priv Browser - Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, windows, chromium-build]

    steps:
      - name: Checkout Priv Browser Repo
        uses: actions/checkout@v4
        with:
          repository: TheTechNetwork/priv-browser

      - name: Setup Depot Tools
        shell: cmd
        run: |
          git config --global core.autocrlf false
          git config --global core.filemode false
          git config --global --add safe.directory C:/priv_browser_build/depot_tools
          git config --global --add safe.directory C:/src/depot_tools
          if not exist C:\priv_browser_build\depot_tools (
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git C:\priv_browser_build\depot_tools
          ) else (
            cd C:\priv_browser_build\depot_tools
            git fetch --all
            git reset --hard origin/main
          )
          echo C:\priv_browser_build\depot_tools >> %GITHUB_PATH%

      - name: Configure `.gclient`
        shell: cmd
        run: |
          if not exist C:\priv_browser_build mkdir C:\priv_browser_build
          echo solutions = [ > C:\priv_browser_build\priv-browser\.gclient
          echo { >> C:\priv_browser_build\priv-browser\.gclient
          echo   "name": "src", >> C:\priv_browser_build\priv-browser\.gclient
          echo   "url": "https://github.com/TheTechNetwork/priv-browser.git", >> C:\priv_browser_build\priv-browser\.gclient
          echo   "deps_file": "DEPS", >> C:\priv_browser_build\priv-browser\.gclient
          echo   "managed": False, >> C:\priv_browser_build\priv-browser\.gclient
          echo   "custom_deps": {}, >> C:\priv_browser_build\priv-browser\.gclient
          echo   "custom_vars": {}, >> C:\priv_browser_build\priv-browser\.gclient
          echo } >> C:\priv_browser_build\priv-browser\.gclient


      - name: Sync Priv Browser Dependencies
        shell: cmd
        run: |
          cd C:\priv_browser_build\priv-browser
          gclient sync --nohooks --with_branch_heads --with_tags
          
      - name: Configure and Build for Windows
        shell: cmd
        run: |
          cd C:\priv_browser_build\priv-browser\src
          gn gen out\Windows --args="target_os=\"win\" target_cpu=\"x64\" is_debug=false"
          ninja -C out\Windows chrome

      - name: Zip Windows Build
        shell: cmd
        run: |
          powershell Compress-Archive -Path C:\priv_browser_build\priv-browser\src\out\Windows\* -DestinationPath C:\priv-browser-windows.zip

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: priv-browser-windows-build
          path: C:\priv-browser-windows.zip
          if-no-files-found: error
